name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-varsion }}
        uses: actions/setup-node@v3
        with:
          node-varsion: ${{ matrix.node-varsion }}
      - name: install modules
        run: npm install
      - name: generate Prisma
        run: npx prisma generate
      - name: apply migrations
        run: npx prisma migrate dev --name init
      - name: build project
        run: npm run build
      - name: test project
        run: npm run test
