name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]  
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} 
    - name: Install dependencies
      run: npm install    
    - name: Setup database
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
      run: |
        npx prisma generate
        npx prisma migrate deploy 
    - name: Run tests
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
      run: npm test
